<template>
  <div
    class="V2Container"
    ref="wrap"
    style="width:100%;height:100%;"
    id="root"
    component="v2Container"
    direction="row"
    layout="100"
  >
    <el-row class="V2ContainerBlock" style="height:100%;width:100%;" key="0">
      <v2container
        is="av-layout-colctn"
        wid="1557729515923"
        index="0"
        pid="root"
        direction="row"
        layout="[50,50]"
        href="av-layout-colctn"
        component="av-layout-colctn"
        id="1557729515923"
      >
        <el-row
          class="V2ContainerBlock borderBox dashBorder"
          style="height:50%;width:100%;"
          key="0"
        >
          <av-form-datepicker
            is="av-form-datePicker"
            wid="1557919551218"
            index="0"
            pid="1557729515923"
            label="标题"
            labelwitdh="80px"
            titlemode="row"
            value="user.name"
            placeholder="请选择"
            type="date"
            disabled="false"
            clearable="true"
            format="yyyy 年 MM 月 dd 日"
            align="left"
            href="av-form-datePicker"
            component="av-form-datePicker"
            id="1557919551218"
          ></av-form-datepicker>
        </el-row>
        <el-row class="V2ContainerBlock" style="height:50%;width:100%;" key="1">
          <v2container
            is="av-layout-colctn"
            wid="1557761115858"
            index="1"
            pid="1557729515923"
            component="av-layout-colctn"
            href="av-layout-colctn"
            layout="50,50"
            direction="row"
            id="1557761115858"
          >
            <el-row
              class="V2ContainerBlock borderBox dashBorder"
              style="height:50%;width:100%;"
              key="0"
            >
              <av-form-radio
                is="av-form-radio"
                wid="1557761115858"
                index="0"
                pid="1557760827010"
                label="标题"
                titlemode="row"
                value
                href="av-form-radio"
                component="av-form-radio"
                id="1557761115858"
                direction="row"
              >
                <div
                  class="V2Empty"
                  is="v2Empty"
                  wid="1557761115858-0"
                  index="0"
                  pid="1557761115858"
                ></div>
                <div
                  class="V2Empty"
                  is="v2Empty"
                  wid="1557761115858-1"
                  index="1"
                  pid="1557761115858"
                ></div>
              </av-form-radio>
            </el-row>
            <el-row
              class="V2ContainerBlock borderBox dashBorder"
              style="height:50%;width:100%;"
              key="1"
            >
              <av-form-input
                is="av-form-input"
                wid="1557760827010"
                index="1"
                pid="1557729515923"
                label="标题"
                titlemode="row"
                labelwitdh="80px"
                placeholder="请选择"
                value
                clearable="false"
                href="av-form-input"
                component="av-form-input"
                id="1557760827010"
              ></av-form-input>
            </el-row>
          </v2container>
        </el-row>
      </v2container>
    </el-row>
  </div>
</template>
<script>
export default {
  data() {
    return {};
  },
  methods: {},
  watch: {}
};
</script>