<template>




  <div
    class="V2Container"
    ref="wrap"
    style="width:100%;height:100%;"
    id="root"
    component="v2Container"
    direction="row"
    layout="100"
  >
    <el-row class="V2ContainerBlock" style="height:100%;width:100%;" key="0">
      <v2container
        is="v2-layout-colctn"
        wid="1557729515923"
        index="0"
        pid="root"
        direction="row"
        layout="[50,50]"
        href="v2-layout-colctn"
        component="v2-layout-colctn"
        id="1557729515923"
      >
        <el-row class="V2ContainerBlock" style="height:50%;width:100%;" key="0">
          <v2container
            is="v2-layout-colctn"
            wid="1557909776144"
            index="0"
            pid="1557729515923"
            component="v2-layout-colctn"
            href="v2-layout-colctn"
            layout="50,50"
            direction="col"
            id="1557909776144"
          >
            <el-col
              class="V2ContainerBlock borderBox dashBorder"
              span="12"
              key="0"
              style="height:100%;"
            >
              <v2-form-cascader
                is="v2-form-cascader"
                wid="1557909764093"
                index="0"
                pid="1557729515923"
                label="标题"
                labelwitdh="80px"
                titlemode="row"
                placeholder="提示文本"
                filterable="true"
                value="[]"
                trigger="click"
                options="[object Object],[object Object]"
                href="v2-form-cascader"
                component="v2-form-cascader"
                id="1557909764093"
              ></v2-form-cascader>
            </el-col>
            <el-col
              class="V2ContainerBlock borderBox dashBorder"
              span="12"
              key="1"
              style="height:100%;"
            >
              <v2-form-cascader
                is="v2-form-cascader"
                wid="1557909776143"
                index="1"
                pid="1557909776144"
                label="标题"
                labelwitdh="80px"
                titlemode="row"
                placeholder="提示文本"
                filterable="true"
                value="[]"
                trigger="click"
                options="[object Object],[object Object]"
                href="v2-form-cascader"
                component="v2-form-cascader"
                id="1557909776143"
              ></v2-form-cascader>
            </el-col>
          </v2container>
        </el-row>
        <el-row class="V2ContainerBlock" style="height:50%;width:100%;" key="1">
          <v2container
            is="v2-layout-colctn"
            wid="1557761115858"
            index="1"
            pid="1557729515923"
            component="v2-layout-colctn"
            href="v2-layout-colctn"
            layout="50,50"
            direction="row"
            id="1557761115858"
          >
            <el-row
              class="V2ContainerBlock borderBox dashBorder"
              style="height:50%;width:100%;"
              key="0"
            >
              <v2-form-radio
                is="v2-form-radio"
                wid="1557761115858"
                index="0"
                pid="1557760827010"
                label="标题"
                titlemode="row"
                value
                options="[object Object],[object Object]"
                href="v2-form-radio"
                component="v2-form-radio"
                id="1557761115858"
                direction="row"
              >
                <v2-form-inputnumber
                  is="v2-form-inputNumber"
                  wid="1557909774435"
                  index="0"
                  pid="1557761115858"
                  label="标题"
                  titlemode="row"
                  value="1"
                  disabled="false"
                  min="1"
                  max="10"
                  step="1"
                  precision="1"
                  href="v2-form-inputNumber"
                  component="v2-form-inputNumber"
                  id="1557909774435"
                ></v2-form-inputnumber>
                <div
                  class="V2Empty"
                  is="v2Empty"
                  wid="1557761115858-1"
                  index="1"
                  pid="1557761115858"
                ></div>
              </v2-form-radio>
            </el-row>
            <el-row
              class="V2ContainerBlock borderBox dashBorder"
              style="height:50%;width:100%;"
              key="1"
            >
              <v2-form-input
                is="v2-form-input"
                wid="1557760827010"
                index="1"
                pid="1557729515923"
                label="标题"
                titlemode="row"
                labelwitdh="80px"
                placeholder="请选择"
                value
                clearable="false"
                href="v2-form-input"
                component="v2-form-input"
                id="1557760827010"
              ></v2-form-input>
            </el-row>
          </v2container>
        </el-row>
      </v2container>
    </el-row>
  </div>
</template>

<script>
export default {
    data(){
        return{
            databasket:{
                A:{
                    user:{
                        name:''
                    }
                }
            }
        }
    },
    computed:{
        'databasket.A.user.name':{
            get(){
              return false;
               // return this.$store.getters.model(id).value;
            }
        }
    }
}
</script>
